language: go

addons:
  apt:
    packages:
      - docker-ce

env: GO111MODULE=on

go:
  - 1.13.x

services:
  - docker

before_script:
  - go build

script:
  - go test
  - cd tests && ./run_tests.sh
